use_frameworks!

platform :ios, '9.0'

target 'AppStoreVersionDetector_Example' do
  pod 'AppStoreVersionDetector', :path => '../'

  target 'AppStoreVersionDetector_Tests' do
    inherit! :search_paths

    
  end
end
